### ISSUE TITLE
segfault when used with fasttext-ruby?

### ISSUE THREAD

**Issue by kmarsh** [ankane/field_test#44]
I've been using field_test 0.5.4 for some time in a Rails 6.1 app, and just added fasttext 0.2.4 to the same app to do some text classification (I'm a big fan of @ankane gems 😉.)

Everything worked fine in development but when I pushed to production I noticed a segfault when booting the app. Because I just added fasttext I suspected it was the issue and spent a fair amount of time debugging but didn't get anywhere. When digging in the stack traces `field_test` came up! 🤔 

Sure enough, removing the gem causes the app to boot OK again. Weird.

The particular A/B experiment we were doing is over, so I'm going to remove field_test to move ahead, but was wondering if you had any ideas.

Thanks!

<details>
<summary>Stack Trace</summary>

<pre>
2023-03-03T13:53:57.2626537Z terminate called after throwing an instance of 'std::bad_any_cast'
2023-03-03T13:53:57.2626877Z   what():  bad any_cast
2023-03-03T13:53:57.2627319Z /usr/local/bundle/gems/fasttext-0.2.4/lib/fasttext/ext.so: [BUG] Segmentation fault at 0x0000000000000000
2023-03-03T13:53:57.2627756Z ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
2023-03-03T13:53:57.2627916Z 
2023-03-03T13:53:57.2628156Z -- Control frame information -----------------------------------------------
2023-03-03T13:53:57.2628533Z c:0030 p:---- s:0146 e:000145 TOP    [FINISH]
2023-03-03T13:53:57.2628839Z c:0029 p:---- s:0143 e:000142 CFUNC  :require
2023-03-03T13:53:57.2629291Z c:0028 p:0006 s:0138 e:000137 BLOCK  /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332
2023-03-03T13:53:57.2629847Z c:0027 p:0039 s:0135 e:000134 METHOD /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299
2023-03-03T13:53:57.2630372Z c:0026 p:0010 s:0128 e:000127 METHOD /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332
2023-03-03T13:53:57.2630866Z c:0025 p:0005 s:0122 e:000121 TOP    /usr/local/bundle/gems/fasttext-0.2.4/lib/fasttext.rb:2 [FINISH]
2023-03-03T13:53:57.2631225Z c:0024 p:---- s:0119 e:000118 CFUNC  :require
2023-03-03T13:53:57.2631641Z c:0023 p:0025 s:0114 e:000113 BLOCK  /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:60 [FINISH]
2023-03-03T13:53:57.2632001Z c:0022 p:---- s:0109 e:000108 CFUNC  :each
2023-03-03T13:53:57.2632421Z c:0021 p:0042 s:0105 e:000104 BLOCK  /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:55 [FINISH]
2023-03-03T13:53:57.2632779Z c:0020 p:---- s:0098 e:000097 CFUNC  :each
2023-03-03T13:53:57.2633171Z c:0019 p:0026 s:0094 e:000093 METHOD /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:44
2023-03-03T13:53:57.2633629Z c:0018 p:0013 s:0089 e:000088 METHOD /usr/local/bundle/gems/bundler-2.4.7/lib/bundler.rb:195
2023-03-03T13:53:57.2633965Z c:0017 p:0076 s:0084 e:000083 TOP    /app/config/application.rb:19 [FINISH]
2023-03-03T13:53:57.2634321Z c:0016 p:---- s:0081 e:000080 CFUNC  :require_relative
2023-03-03T13:53:57.2634603Z c:0015 p:0005 s:0076 e:000075 TOP    /app/Rakefile:4 [FINISH]
2023-03-03T13:53:57.2634905Z c:0014 p:---- s:0073 e:000072 CFUNC  :load
2023-03-03T13:53:57.2642960Z c:0013 p:0005 s:0068 e:000067 METHOD /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29
2023-03-03T13:53:57.2643476Z c:0012 p:0141 s:0063 e:000062 METHOD /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:710
2023-03-03T13:53:57.2643989Z c:0011 p:0003 s:0057 e:000056 BLOCK  /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:104
2023-03-03T13:53:57.2644474Z c:0010 p:0002 s:0054 e:000053 METHOD /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186
2023-03-03T13:53:57.2644958Z c:0009 p:0004 s:0049 e:000048 METHOD /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:103
2023-03-03T13:53:57.2645464Z c:0008 p:0019 s:0045 e:000044 BLOCK  /usr/local/bundle/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:20
2023-03-03T13:53:57.2645978Z c:0007 p:0023 s:0041 e:000040 METHOD /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59
2023-03-03T13:53:57.2646473Z c:0006 p:0009 s:0035 e:000034 METHOD /usr/local/bundle/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:18
2023-03-03T13:53:57.2647022Z c:0005 p:0143 s:0028 e:000027 METHOD /usr/local/bundle/gems/railties-6.1.7/lib/rails/command.rb:50
2023-03-03T13:53:57.2647636Z c:0004 p:0038 s:0016 e:000015 TOP    /usr/local/bundle/gems/railties-6.1.7/lib/rails/commands.rb:18 [FINISH]
2023-03-03T13:53:57.2648014Z c:0003 p:---- s:0011 e:000010 CFUNC  :require
2023-03-03T13:53:57.2648282Z c:0002 p:0024 s:0006 e:000005 EVAL   bin/rails:4 [FINISH]
2023-03-03T13:53:57.2648547Z c:0001 p:0000 s:0003 E:000590 DUMMY  [FINISH]
2023-03-03T13:53:57.2648695Z 
2023-03-03T13:53:57.2648931Z -- Ruby level backtrace information ----------------------------------------
2023-03-03T13:53:57.2649207Z bin/rails:4:in `<main>'
2023-03-03T13:53:57.2649421Z bin/rails:4:in `require'
2023-03-03T13:53:57.2649807Z /usr/local/bundle/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<top (required)>'
2023-03-03T13:53:57.2650238Z /usr/local/bundle/gems/railties-6.1.7/lib/rails/command.rb:50:in `invoke'
2023-03-03T13:53:57.2650685Z /usr/local/bundle/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
2023-03-03T13:53:57.2651168Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
2023-03-03T13:53:57.2651667Z /usr/local/bundle/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
2023-03-03T13:53:57.2652153Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
2023-03-03T13:53:57.2652637Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
2023-03-03T13:53:57.2653134Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
2023-03-03T13:53:57.2653613Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
2023-03-03T13:53:57.2654078Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
2023-03-03T13:53:57.2654516Z /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
2023-03-03T13:53:57.2654804Z /app/Rakefile:4:in `<top (required)>'
2023-03-03T13:53:57.2655101Z /app/Rakefile:4:in `require_relative'
2023-03-03T13:53:57.2655380Z /app/config/application.rb:19:in `<top (required)>'
2023-03-03T13:53:57.2655766Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler.rb:195:in `require'
2023-03-03T13:53:57.2656163Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:44:in `require'
2023-03-03T13:53:57.2656571Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:44:in `each'
2023-03-03T13:53:57.2656998Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:55:in `block in require'
2023-03-03T13:53:57.2657421Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:55:in `each'
2023-03-03T13:53:57.2657984Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
2023-03-03T13:53:57.2658500Z /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/runtime.rb:60:in `require'
2023-03-03T13:53:57.2658925Z /usr/local/bundle/gems/fasttext-0.2.4/lib/fasttext.rb:2:in `<top (required)>'
2023-03-03T13:53:57.2659403Z /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
2023-03-03T13:53:57.2659923Z /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
2023-03-03T13:53:57.2660437Z /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
2023-03-03T13:53:57.2660936Z /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
2023-03-03T13:53:57.2661158Z 
2023-03-03T13:53:57.2661396Z -- Machine register context ------------------------------------------------
2023-03-03T13:53:57.2661743Z  RIP: 0x00007fd1305cd611 RBP: 0x00007fd130766840 RSP: 0x00007ffe7b7a1d90
2023-03-03T13:53:57.2662050Z  RAX: 0x0000000000000000 RBX: 0x00007fd128ef5000 RCX: 0x0000000000000000
2023-03-03T13:53:57.2662332Z  RDX: 0x0000000000000000 RDI: 0x0000000000000002 RSI: 0x00007ffe7b7a1c70
2023-03-03T13:53:57.2662617Z   R8: 0x0000000000000000  R9: 0x00007ffe7b7a1c70 R10: 0x0000000000000008
2023-03-03T13:53:57.2662887Z  R11: 0x0000000000000246 R12: 0x000056287ca8aa30 R13: 0x0000000000000008
2023-03-03T13:53:57.2663203Z  R14: 0x00007fd1303fcd08 R15: 0x00007fd129685748 EFL: 0x0000000000010246
2023-03-03T13:53:57.2663366Z 
2023-03-03T13:53:57.2663589Z -- C level backtrace information -------------------------------------------
2023-03-03T13:53:57.6672095Z /usr/local/lib/libruby.so.3.2(rb_print_backtrace+0x11) [0x7fd130d31280] vm_dump.c:785
2023-03-03T13:53:57.6672488Z /usr/local/lib/libruby.so.3.2(rb_vm_bugreport) vm_dump.c:1080
2023-03-03T13:53:57.6672844Z /usr/local/lib/libruby.so.3.2(rb_bug_for_fatal_signal+0xf0) [0x7fd130b505b0] error.c:813
2023-03-03T13:53:57.6673200Z /usr/local/lib/libruby.so.3.2(sigsegv+0x4b) [0x7fd130c94aab] signal.c:964
2023-03-03T13:53:57.6673817Z /lib/x86_64-linux-gnu/libpthread.so.0(__restore_rt+0x0) [0x7fd13077d730]
2023-03-03T13:53:57.6674205Z /lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd) [0x7fd1305cd611]
2023-03-03T13:53:57.6674600Z /usr/lib/x86_64-linux-gnu/libstdc++.so.6(0x7fd129c31983) [0x7fd129c31983]
2023-03-03T13:53:57.6675004Z /usr/lib/x86_64-linux-gnu/libstdc++.so.6(0x7fd129c378c6) [0x7fd129c378c6]
2023-03-03T13:53:57.6675440Z /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt9terminatev+0x11) [0x7fd129c37901]
2023-03-03T13:53:57.6675861Z /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_throw+0x44) [0x7fd129c37b34]
2023-03-03T13:53:57.6684047Z /usr/local/bundle/gems/field_test-0.5.4/lib/field_test/ext.so(_ZSt20__throw_bad_any_castv+0x32) [0x7fd128ed21c2]
2023-03-03T13:53:57.6684863Z /usr/local/bundle/gems/fasttext-0.2.4/lib/fasttext/ext.so(_ZN4Rice6detail12RubyFunctionIPFmPKcEmJS3_EEclEv+0x62) [0x7fd128da0c72]
2023-03-03T13:53:57.6685406Z /usr/local/bundle/gems/fasttext-0.2.4/lib/fasttext/ext.so(Init_ext+0x48) [0x7fd128d98bf8]
2023-03-03T13:53:57.6685771Z /usr/local/lib/libruby.so.3.2(dln_load+0x127) [0x7fd130aba927] dln.c:472
2023-03-03T13:53:57.6686239Z /usr/local/lib/libruby.so.3.2(rb_vm_pop_frame+0x0) [0x7fd130d184e1] vm.c:2679
2023-03-03T13:53:57.6686546Z /usr/local/lib/libruby.so.3.2(rb_vm_call_cfunc) vm.c:2681
2023-03-03T13:53:57.6687037Z /usr/local/lib/libruby.so.3.2(rb_long2num_inline+0x0) [0x7fd130bbde95] load.c:1208
2023-03-03T13:53:57.6687372Z /usr/local/lib/libruby.so.3.2(require_internal) load.c:1210
2023-03-03T13:53:57.6687700Z /usr/local/lib/libruby.so.3.2(rb_require_string+0x3d) [0x7fd130bbeacd] load.c:1293
2023-03-03T13:53:57.6688073Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6688466Z /usr/local/lib/libruby.so.3.2(vm_call_method_each_type+0xe6) [0x7fd130d27ff6] vm_insnhelper.c:3904
2023-03-03T13:53:57.6688842Z /usr/local/lib/libruby.so.3.2(vm_call_alias+0x69) [0x7fd130d28e29] vm_insnhelper.c:3431
2023-03-03T13:53:57.6689205Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1bdb3] vm_insnhelper.c:5069
2023-03-03T13:53:57.6689804Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:922
2023-03-03T13:53:57.6690111Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0xbb) [0x7fd130d1f75b] vm.c:2374
2023-03-03T13:53:57.6690453Z /usr/local/lib/libruby.so.3.2(load_iseq_eval+0x21) [0x7fd130bbe022] load.c:697
2023-03-03T13:53:57.6690775Z /usr/local/lib/libruby.so.3.2(require_internal) load.c:1202
2023-03-03T13:53:57.6691107Z /usr/local/lib/libruby.so.3.2(rb_require_string+0x3d) [0x7fd130bbeacd] load.c:1293
2023-03-03T13:53:57.6691473Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6691868Z /usr/local/lib/libruby.so.3.2(vm_call_method_each_type+0xe6) [0x7fd130d27ff6] vm_insnhelper.c:3904
2023-03-03T13:53:57.6692238Z /usr/local/lib/libruby.so.3.2(vm_call_alias+0x69) [0x7fd130d28e29] vm_insnhelper.c:3431
2023-03-03T13:53:57.6692598Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1a21d] vm_insnhelper.c:5064
2023-03-03T13:53:57.6692952Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:820
2023-03-03T13:53:57.6693251Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0xbb) [0x7fd130d1f75b] vm.c:2374
2023-03-03T13:53:57.6693582Z /usr/local/lib/libruby.so.3.2(invoke_block+0x60) [0x7fd130d2c70e] vm.c:1398
2023-03-03T13:53:57.6693958Z /usr/local/lib/libruby.so.3.2(rb_yield) vm.c:1454
2023-03-03T13:53:57.6694271Z /usr/local/lib/libruby.so.3.2(RB_FL_TEST_RAW+0x0) [0x7fd130abc72c] array.c:2740
2023-03-03T13:53:57.6694625Z /usr/local/lib/libruby.so.3.2(RB_FL_ANY_RAW) ./include/ruby/internal/fl_type.h:552
2023-03-03T13:53:57.6694980Z /usr/local/lib/libruby.so.3.2(rb_array_len) ./include/ruby/internal/core/rarray.h:321
2023-03-03T13:53:57.6695301Z /usr/local/lib/libruby.so.3.2(rb_ary_each) array.c:2739
2023-03-03T13:53:57.6695642Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6696010Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1a327] vm_insnhelper.c:5064
2023-03-03T13:53:57.6696322Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:801
2023-03-03T13:53:57.6696628Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0xbb) [0x7fd130d1f75b] vm.c:2374
2023-03-03T13:53:57.6696948Z /usr/local/lib/libruby.so.3.2(invoke_block+0x60) [0x7fd130d2c70e] vm.c:1398
2023-03-03T13:53:57.6697248Z /usr/local/lib/libruby.so.3.2(rb_yield) vm.c:1454
2023-03-03T13:53:57.6697688Z /usr/local/lib/libruby.so.3.2(RB_FL_TEST_RAW+0x0) [0x7fd130abc72c] array.c:2740
2023-03-03T13:53:57.6698045Z /usr/local/lib/libruby.so.3.2(RB_FL_ANY_RAW) ./include/ruby/internal/fl_type.h:552
2023-03-03T13:53:57.6698408Z /usr/local/lib/libruby.so.3.2(rb_array_len) ./include/ruby/internal/core/rarray.h:321
2023-03-03T13:53:57.6698740Z /usr/local/lib/libruby.so.3.2(rb_ary_each) array.c:2739
2023-03-03T13:53:57.6699211Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6699583Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1a327] vm_insnhelper.c:5064
2023-03-03T13:53:57.6700035Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:801
2023-03-03T13:53:57.6700352Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0xbb) [0x7fd130d1f75b] vm.c:2374
2023-03-03T13:53:57.6700681Z /usr/local/lib/libruby.so.3.2(load_iseq_eval+0x21) [0x7fd130bbe022] load.c:697
2023-03-03T13:53:57.6700995Z /usr/local/lib/libruby.so.3.2(require_internal) load.c:1202
2023-03-03T13:53:57.6701328Z /usr/local/lib/libruby.so.3.2(rb_require_string+0x3d) [0x7fd130bbeacd] load.c:1293
2023-03-03T13:53:57.6701701Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6702072Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1a21d] vm_insnhelper.c:5064
2023-03-03T13:53:57.6703082Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:820
2023-03-03T13:53:57.6703403Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0xbb) [0x7fd130d1f75b] vm.c:2374
2023-03-03T13:53:57.6703741Z /usr/local/lib/libruby.so.3.2(raise_load_if_failed+0x0) [0x7fd130bbd1d4] load.c:697
2023-03-03T13:53:57.6704197Z /usr/local/lib/libruby.so.3.2(rb_load_internal) load.c:760
2023-03-03T13:53:57.6704486Z /usr/local/lib/libruby.so.3.2(rb_f_load) load.c:833
2023-03-03T13:53:57.6704828Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6705207Z /usr/local/lib/libruby.so.3.2(vm_call_method_each_type+0xe6) [0x7fd130d27ff6] vm_insnhelper.c:3904
2023-03-03T13:53:57.6705594Z /usr/local/lib/libruby.so.3.2(vm_call_method+0xc4) [0x7fd130d289b4] vm_insnhelper.c:4054
2023-03-03T13:53:57.6705957Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1a21d] vm_insnhelper.c:5064
2023-03-03T13:53:57.6706272Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:820
2023-03-03T13:53:57.6706581Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0x706) [0x7fd130d1fda6] vm.c:2383
2023-03-03T13:53:57.6706914Z /usr/local/lib/libruby.so.3.2(load_iseq_eval+0x21) [0x7fd130bbe022] load.c:697
2023-03-03T13:53:57.6707224Z /usr/local/lib/libruby.so.3.2(require_internal) load.c:1202
2023-03-03T13:53:57.6707548Z /usr/local/lib/libruby.so.3.2(rb_require_string+0x3d) [0x7fd130bbeacd] load.c:1293
2023-03-03T13:53:57.6707915Z /usr/local/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0xe2) [0x7fd130d0cf82] vm_insnhelper.c:3252
2023-03-03T13:53:57.6708342Z /usr/local/lib/libruby.so.3.2(vm_call_method_each_type+0xe6) [0x7fd130d27ff6] vm_insnhelper.c:3904
2023-03-03T13:53:57.6708712Z /usr/local/lib/libruby.so.3.2(vm_call_alias+0x69) [0x7fd130d28e29] vm_insnhelper.c:3431
2023-03-03T13:53:57.6709082Z /usr/local/lib/libruby.so.3.2(vm_call_method_each_type+0x2be) [0x7fd130d281ce] vm_insnhelper.c:3965
2023-03-03T13:53:57.6709453Z /usr/local/lib/libruby.so.3.2(vm_call_method+0xc4) [0x7fd130d289b4] vm_insnhelper.c:4054
2023-03-03T13:53:57.6728422Z /usr/local/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fd130d1a21d] vm_insnhelper.c:5064
2023-03-03T13:53:57.6729186Z /usr/local/lib/libruby.so.3.2(vm_exec_core) insns.def:820
2023-03-03T13:53:57.6729502Z /usr/local/lib/libruby.so.3.2(rb_vm_exec+0xbb) [0x7fd130d1f75b] vm.c:2374
2023-03-03T13:53:57.6730016Z /usr/local/lib/libruby.so.3.2(rb_ec_exec_node+0xab) [0x7fd130b5548b] eval.c:289
2023-03-03T13:53:57.6730347Z /usr/local/lib/libruby.so.3.2(ruby_run_node+0x8b) [0x7fd130b5b77b] eval.c:330
2023-03-03T13:53:57.6730659Z /usr/local/bin/ruby(rb_main+0x21) [0x5628770d5112] ./main.c:38
2023-03-03T13:53:57.6730915Z /usr/local/bin/ruby(main) ./main.c:57
2023-03-03T13:53:57.6731341Z /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fd1305cf09b]
2023-03-03T13:53:57.6731594Z [0x5628770d515a]
2023-03-03T13:53:57.6731710Z
</pre>

</details>

**Comment by ankane** [comment]
Hey @kmarsh, thanks for the great report! Not sure when I'll be able to dig into this, but does seem like something odd is going on.

**Comment by ankane** [comment]
Hi @kmarsh, I'm having trouble reproducing. Can you share more information about your environment (OS + version, how Ruby was installed, which command segfaults)? Also, can you see if it still happens when Bootsnap and Spring are disabled?

**Comment by ankane** [comment]
Happy to revisit when there's enough info to reproduce.

**Comment by ankane** [comment]
Just fyi, found and fixed the cause (https://github.com/ruby-rice/rice/pull/208).
